version: "3.8"
services:
  postgres:
    image: postgres:13.3
    container_name: database
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "release"
      POSTGRES_PASSWORD: "horse_ate_green_guinea_pig"
    ports:
      - "5432:5432" # проброшены для дебага и удобства разработки, на релизе убрать
    networks:
      - net1
#  flowers_backend:
#    container_name: flowers_backend
#    depends_on: 
#      - postgres
#    build: ./backend
#    ports:
#      - "8453:8453"
#    networks:
#      - net1
networks:
  net1:
    driver: bridge